### PR TITLE
Corrected spelling mistakes

### PR DESCRIPTION
**Pull request by Heartbroken-Git**
Hi,

Having downloaded the app to input characters and use its green box I noticed quite a few spelling mistakes. Having seen that the XML was available on GitHub I went around and edited the mistakes out.

**Please note that I did edit the string names as well when they too contained a mistake**. You may have to edit a slightly your code on your end to not break said strings or ignore that part of the change entirely.

P.-S. : Your repository doesn't contain a license, I hope I didn't overstep, if I did please say so and I'll remove both the PR and my fork. Otherwise it would be nice if you could choose an open-source license.

P.-P.-S. : I do own both the *Agent's Handbook* and *The Complex* booklet should you be interested in adding new professions.

### CODE REVIEW

**Comment by arnoid** [comment]
@Heartbroken-Git , I will review this later.
No license)))

I do own both books too  and indeed i want to add new professions, but that stuff could violate the ArcDream licenses. I'll contact them later.

P.S. For now main goal is to finish with real random generation for homicide crime scene generation - something for adventure starts. This release should contain your fixes.

P.P.S. Next milestone is inventory (which is back of the agent page) this is needed for "Advanced" agents

P.P.P.S. you can join discord https://discord.gg/eJsH86 I'm posting some preliminary development results there

**Review by arnoid — APPROVED** [review]
Cos' I'm not native en-speaker, i've double-checked with wiki names of departments.
Looks fine.

While I would keep this PR for a while, cos' I need to update keys in the app. This will not break the app, cos' those keys are not used. I will create a ticket for pulling this PR in my system.

**Comment by Heartbroken-Git** [comment]
Perfect then, glad to have been of any help :slightly_smiling_face:

**Review by arnoid — APPROVED** [review]

**Comment by arnoid** [comment]
Merged and pulled into app

**Pull request merged**
